export const insights = [
    {
        slug: "shoppoint-brand-story-part-1",
        title: "I Broke Up With Him Because of Receipts. I Wish I Didn’t. (Part 1)",
        category: "Brand Story",
        readTime: "4 min read",
        author: "Hannah Oyiza Salami",
        date: "March 03, 2026",
        content: [
            "I broke up with my boyfriend back in university for what I can now admit was a very ridiculous reason and it’s something I still regret to this day.",
            "Looking back, I honestly cannot believe I let something so small make me walk away from someone who was calm, gentle, and genuinely kind. At the time, it felt like a big deal. It felt important, like I was making the right decision for myself.",
            "But now… I know better.",
            "Tunde, if you ever see this, I miss you.",
            "He was one of those rare people who made you feel safe without even trying. Quiet, soft-spoken, not loud or dramatic, just steady. The kind of person you don’t fully appreciate until they’re no longer in your life.",
            "And yes, he didn’t have much at the time. He was trying, managing what he had, but nothing that should have mattered in the long run.",
            "But there was one thing. A habit.",
            "And it got to me more than it should have.",
            "At first, I brushed it off. I even found it a little funny. But over time, it started to irritate me. Every single time we went out and spent money, he kept the receipt. Not sometimes. Every single time.",
            "There was a day we went shopping together, nothing serious, just a normal outing. The cashier forgot to give him a receipt, and this man actually went back to argue about it.",
            "I remember thinking, “It’s just a receipt. Why is this such a big deal?” But to him, it clearly wasn’t just paper.",
            "That was when the irritation really started.",
            "I became frustrated, confused, and if I’m being honest, a little embarrassed. I felt like I couldn’t just enjoy a simple outing without something small turning into something unnecessary.",
            "I didn’t understand it at all.",
            "In my head, I started creating my own explanations. Maybe he was too broke. Maybe he was overly cautious. Maybe he was just… too much.",
            "And instead of asking him, I judged him. That’s the part I regret the most.",
            "I even told my friends about it. We laughed about it at first, but then one of them got serious and said, “If he’s like this now, imagine what the future will look like. You should think about it.”",
            "That sentence stayed with me.",
            "And instead of questioning it, I accepted it.",
            "Not long after, I broke up with him.",
            "There was no fight. No real conversation. I just told him I couldn’t continue. I convinced myself it was the right decision, that I was choosing peace, that I deserved better.",
            "At the time, I even felt relieved.",
            "But deep down, something didn’t sit right.",
            "Days passed, and I tried to move on. Focus on school, on my friends, on everything else. But I kept thinking about him. His calmness. His patience. The little ways he showed he cared.",
            "I started replaying moments in my head. The way he smiled when he saw me. The way he handled me, even when I was being difficult. The small details he remembered about me without trying.",
            "And it hit me. I ended something real… because of receipts.",
            "It sounds ridiculous even writing it now.",
            "The truth is, I should have asked him. I should have had a conversation instead of making assumptions. But I didn’t.",
            "And slowly, I started to miss him.",
            "Not just his presence, but everything that came with him. Even the little “chaos” I once complained about. The kind that makes moments stick in your memory long after they happen.",
            "I started questioning my decision. Maybe I was too harsh. Maybe I didn’t understand him at all.",
            "And that’s when it became clear to me… the problem was never really the receipts.",
            "It was my lack of understanding.",
            "I didn’t take the time to see things from his perspective. I didn’t try to understand where he was coming from or why it mattered to him.",
            "I just judged, reacted, and left.",
            "Now when I think about it, I laugh and feel sad at the same time. It was petty, yes. But it cost me someone who was actually good for me.",
            "And at the time, I didn’t know there was more to it.",
            "Not until I went home."
        ]
    },
    {
        slug: "shoppoint-brand-story-part-2",
        title: "I Broke Up With Him Because of Receipts. I Wish I Didn’t. (Part 2)",
        category: "Brand Story",
        readTime: "3 min read",
        author: "Hannah Oyiza Salami",
        date: "March 03, 2026",
        content: [
            "After the breakup, I was still trying to process everything. When he asked me why I ended things, I couldn’t even bring myself to explain properly.",
            "How do you tell someone you left them because of receipts?",
            "So I said the easiest thing I could think of. “I’m just tired. I’m not comfortable anymore. I need a break.”",
            "I thought that would give closure. It didn’t. It only left him confused, and me, still thinking.",
            "Not long after, I went back home. I needed a break from everything. A different environment. Some peace.",
            "But instead, I walked into something I wasn’t expecting.",
            "A few weeks in, I started noticing something strange.",
            "My dad began asking me for receipts. For everything. Every single errand.",
            "At first, I laughed it off. I thought maybe he was joking. But he wasn’t. It became consistent.",
            "And then my mum joined in. “Don’t forget the receipt,” she would say casually, like it was nothing.",
            "I was confused. Then I became frustrated. Then I started taking it personally.",
            "I began to feel like they didn’t trust me anymore.",
            "I kept asking myself, “Did I do something wrong?” It didn’t make sense. Everywhere I turned, it was the same thing. Receipts. It felt like I couldn’t escape it.",
            "One day, after holding it in for so long, I broke down and asked my mum. “Why is everyone asking me for receipts? Do you people not trust me anymore?”",
            "She was shocked. She didn’t even realize how much it had been affecting me.",
            "Then she explained.",
            "She told me about an app a friend introduced her to called Shoppoint.",
            "At first, I didn’t understand. Then she broke it down.",
            "“You snap your receipts, and you earn rewards. Cashback. You can use it to buy airtime, pay bills, even track your spending.”",
            "I just sat there. All this time, I thought it was about trust. It wasn’t. It was practical.",
            "And immediately, my mind went back to Tunde.",
            "I felt it. That realization. Maybe… he was doing the same thing.",
            "I decided to try it.",
            "I snapped a receipt after buying fuel that evening, and it actually worked. I got rewarded. It tracked everything.",
            "I just sat there laughing at myself.",
            "Because the same thing I ended a relationship over… I was now doing myself.",
            "That was when it really hit me.",
            "He wasn’t being difficult. He was being smart.",
            "And I misunderstood him completely."
        ]
    },
    {
        slug: "shoppoint-brand-story-part-3",
        title: "I Broke Up With Him Because of Receipts. I Wish I Didn’t. (Part 3 - Tunde and Annie’s POV)",
        category: "Brand Story",
        readTime: "3 min read",
        author: "Hannah Oyiza Salami",
        date: "March 03, 2026",
        content: [
            "TUNDE:",
            "I’ve seen people talking about this story, trying to find the guy who was “too serious about receipts.”",
            "Well, I’m here. My name is Tunde, and I think it’s only fair I say my side. Because from where I stood, it wasn’t funny.",
            "It was confusing, and honestly, painful.",
            "When Annie broke up with me, there was no proper explanation. No real conversation. One moment we were fine, the next, everything ended.",
            "She said she was tired. That was all.",
            "And I kept asking myself what I did wrong.",
            "Later, I heard it was because of receipts.",
            "What hurt me wasn’t even the fact that she found it annoying. It was that she never asked me why.",
            "Receipts have saved me more times than I can count.",
            "There was a time I was almost overcharged, and I only realized because I checked. Another time, my landlord claimed I didn’t complete my rent. The only thing that saved me was a receipt I had snapped and kept.",
            "So yes, it became a habit. Not obsession. Just responsibility.",
            "Life is already hard. Keeping track of your money gives you some control.",
            "After the breakup, I was hurt, but life didn’t stop. I kept going. And eventually, I moved on.",
            "The girl I’m with now was my friend before everything happened. She understood me without me having to explain too much.",
            "So when Annie came back to apologize, I listened. But I had already moved on.",
            "And I told her the truth.",
            "ANNIE:",
            "When I finally reached out to him, I thought understanding would fix everything.",
            "But it didn’t. He had already built something else. And I was too late.",
            "That was the hardest part. Realizing I didn’t lose him because of something big… But because I didn’t ask questions when I should have.",
            "Now, I’ve learned. Not to judge quickly. Not to let outside opinions make decisions for me. And most importantly, to understand before reacting.",
            "These days, I keep receipts too. I track my spending. I even earn from it.",
            "And every time I do, I think of him.",
            "Life has a funny way of teaching lessons. Sometimes, it just comes a little too late."
        ]
    }
];
